version: '3.8'
services:
  db_bp:
    image: mysql:8.0
    container_name: db_bp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: "no"

volumes:
  db_data:
