version: '3.8'

services:
  db_bp:
    image: mysql:8.0
    container_name: db_bp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - '3307:3306'
    networks:
      - bp_net

  api_bp:  # <-- ¡debe estar al mismo nivel que db_bp!
    build: .
    container_name: api_bp
    ports:
      - '3000:3000'
    depends_on:
      - db_bp
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_JWT_SEED: ${SECRET_JWT_SEED}
      HOST: ${HOST}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - bp_net
      - proxy

networks:
  bp_net:
  proxy:
    external: true
