-- CreateTable
CREATE TABLE `BP_01_USUARIO` (
    `nId01Usuario` INTEGER NOT NULL AUTO_INCREMENT,
    `sNombre` VARCHAR(191) NOT NULL,
    `sApellidoPaterno` VARCHAR(191) NOT NULL,
    `sApellidoMaterno` VARCHAR(191) NOT NULL,
    `sUsuario` VARCHAR(191) NOT NULL,
    `sEmail` VARCHAR(191) NOT NULL,
    `sPassword` VARCHAR(191) NOT NULL,
    `bActivo` BOOLEAN NOT NULL DEFAULT false,
    `dFechaCreacion` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `dFechaActualizacion` DATETIME(3) NULL,

    UNIQUE INDEX `BP_01_USUARIO_sUsuario_key`(`sUsuario`),
    UNIQUE INDEX `BP_01_USUARIO_sEmail_key`(`sEmail`),
    PRIMARY KEY (`nId01Usuario`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BP_02_PERFIL` (
    `nId02Perfil` INTEGER NOT NULL AUTO_INCREMENT,
    `sNombre` VARCHAR(191) NOT NULL,
    `sDescripcion` VARCHAR(191) NOT NULL,
    `dFechaCreacion` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `dFechaActualizacion` DATETIME(3) NULL,

    UNIQUE INDEX `BP_02_PERFIL_sNombre_key`(`sNombre`),
    PRIMARY KEY (`nId02Perfil`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BP_03_PERMISO` (
    `nId03Permiso` INTEGER NOT NULL AUTO_INCREMENT,
    `sNombre` VARCHAR(191) NOT NULL,
    `sDescripcion` VARCHAR(191) NOT NULL,
    `dFechaCreacion` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `dFechaActualizacion` DATETIME(3) NULL,

    UNIQUE INDEX `BP_03_PERMISO_sNombre_key`(`sNombre`),
    PRIMARY KEY (`nId03Permiso`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BP_04_PERFIL_USUARIO` (
    `nId04PerfilUsuario` INTEGER NOT NULL AUTO_INCREMENT,
    `nId01Usuario` INTEGER NOT NULL,
    `nId02Perfil` INTEGER NOT NULL,
    `dFechaCreacion` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `dFechaActualizacion` DATETIME(3) NULL,

    PRIMARY KEY (`nId04PerfilUsuario`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BP_05_PERFIL_PERMISO` (
    `nId05PerfilPermiso` INTEGER NOT NULL AUTO_INCREMENT,
    `nId03Permiso` INTEGER NOT NULL,
    `nId02Perfil` INTEGER NOT NULL,
    `nLeer` BOOLEAN NOT NULL DEFAULT false,
    `nCrear` BOOLEAN NOT NULL DEFAULT false,
    `nEditar` BOOLEAN NOT NULL DEFAULT false,
    `nBorrar` BOOLEAN NOT NULL DEFAULT false,
    `dFechaCreacion` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `dFechaActualizacion` DATETIME(3) NULL,

    PRIMARY KEY (`nId05PerfilPermiso`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `BP_04_PERFIL_USUARIO` ADD CONSTRAINT `BP_04_PERFIL_USUARIO_nId01Usuario_fkey` FOREIGN KEY (`nId01Usuario`) REFERENCES `BP_01_USUARIO`(`nId01Usuario`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BP_04_PERFIL_USUARIO` ADD CONSTRAINT `BP_04_PERFIL_USUARIO_nId02Perfil_fkey` FOREIGN KEY (`nId02Perfil`) REFERENCES `BP_02_PERFIL`(`nId02Perfil`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BP_05_PERFIL_PERMISO` ADD CONSTRAINT `BP_05_PERFIL_PERMISO_nId03Permiso_fkey` FOREIGN KEY (`nId03Permiso`) REFERENCES `BP_03_PERMISO`(`nId03Permiso`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BP_05_PERFIL_PERMISO` ADD CONSTRAINT `BP_05_PERFIL_PERMISO_nId02Perfil_fkey` FOREIGN KEY (`nId02Perfil`) REFERENCES `BP_02_PERFIL`(`nId02Perfil`) ON DELETE RESTRICT ON UPDATE CASCADE;
