name: CI/CD Node Deploy

on:
  push:
    branches:
      - SISTEMA-CLIENTES-VENTAS

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote SSH commands for Sistema Ventas
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }} # Solo si la clave está protegida
          port:  ${{ secrets.SSH_PORT }} 
          script: |
            cd ${{ secrets.WORK_DIR }}

            echo "📥 Actualizando repositorio..."
            git fetch origin
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull ${{ secrets.MAIN_BRANCH }}

            # echo "🐳 Reconstruyendo contenedores Docker..."
            docker compose down
            docker compose up -d --build

            # echo "Prueba1"

