name: CI/CD PHP Node Deploy

on:
  push:
    branches:
      - SISTEMA-CLIENTES-VENTAS

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote SSH commands for Sistema Ventas
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}
